-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    ["exec"] = {
    },
    ["mail"] = {
    },
    ["date"] = {
        ["date_format"] = "%a %m/%d %H:%M",
    },
    ["load"] = {
        ["update_interval"] = 10000,
        ["critical_threshold"] = 4,
        ["important_threshold"] = 1.5,
    },
}

