-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["name"] = "WScreen",
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["y"] = 0,
                    ["h"] = 2160,
                    ["w"] = 3840,
                    ["x"] = 0,
                },
                ["switchto"] = true,
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["h"] = 2160,
                            ["w"] = 3840,
                            ["x"] = 0,
                        },
                        ["level"] = 0,
                        ["name"] = "WTiling",
                        ["type"] = "WTiling",
                        ["split_tree"] = {
                            ["br"] = {
                                ["br"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["name"] = "WFrame<1>",
                                        ["type"] = "WFrame",
                                        ["managed"] = {
                                            [1] = {
                                                ["hidden"] = true,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 4,
                                                        ["bottom"] = true,
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["geom"] = {
                                                            ["y"] = 0,
                                                            ["h"] = 2111,
                                                            ["w"] = 1918,
                                                            ["x"] = 0,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 4194356,
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["h"] = 2111,
                                                    ["w"] = 1918,
                                                    ["x"] = 1,
                                                },
                                                ["level"] = 0,
                                                ["name"] = "WGroupCW",
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                            },
                                            [2] = {
                                                ["switchto"] = true,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 5,
                                                        ["bottom"] = true,
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["geom"] = {
                                                            ["y"] = 0,
                                                            ["h"] = 2111,
                                                            ["w"] = 1918,
                                                            ["x"] = 0,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 16777232,
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["h"] = 2111,
                                                    ["w"] = 1918,
                                                    ["x"] = 1,
                                                },
                                                ["level"] = 0,
                                                ["name"] = "WGroupCW<4>",
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                            },
                                        },
                                    },
                                },
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["name"] = "WFrame",
                                        ["type"] = "WFrame",
                                        ["managed"] = {
                                            [1] = {
                                                ["switchto"] = true,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 1,
                                                        ["bottom"] = true,
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["geom"] = {
                                                            ["y"] = 13,
                                                            ["h"] = 2084,
                                                            ["w"] = 1908,
                                                            ["x"] = 5,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 6291471,
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["h"] = 2111,
                                                    ["w"] = 1918,
                                                    ["x"] = 1,
                                                },
                                                ["level"] = 0,
                                                ["name"] = "WGroupCW<1>",
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                            },
                                            [2] = {
                                                ["hidden"] = true,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 2,
                                                        ["bottom"] = true,
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["geom"] = {
                                                            ["y"] = 13,
                                                            ["h"] = 2084,
                                                            ["w"] = 1908,
                                                            ["x"] = 5,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 8388623,
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["h"] = 2111,
                                                    ["w"] = 1918,
                                                    ["x"] = 1,
                                                },
                                                ["level"] = 0,
                                                ["name"] = "WGroupCW<2>",
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                            },
                                            [3] = {
                                                ["hidden"] = true,
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 3,
                                                        ["bottom"] = true,
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["geom"] = {
                                                            ["y"] = 0,
                                                            ["h"] = 2111,
                                                            ["w"] = 1918,
                                                            ["x"] = 0,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 16777217,
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["h"] = 2111,
                                                    ["w"] = 1918,
                                                    ["x"] = 1,
                                                },
                                                ["level"] = 0,
                                                ["name"] = "WGroupCW<3>",
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                            },
                                        },
                                    },
                                },
                                ["tls"] = 1920,
                                ["brs"] = 1920,
                                ["type"] = "WSplitSplit",
                                ["dir"] = "horizontal",
                            },
                            ["tl"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tls"] = 29,
                            ["brs"] = 2131,
                            ["type"] = "WSplitSplit",
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["initial_outputs"] = {
                    [1] = "HDMI-0",
                },
                ["level"] = 0,
                ["name"] = "WGroupWS",
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
            },
            [2] = {
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 840,
                            ["h"] = 480,
                            ["w"] = 640,
                            ["x"] = 1600,
                        },
                        ["bottom"] = true,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                        ["level"] = 1025,
                        ["name"] = "*scratchpad*",
                        ["type"] = "WFrame",
                        ["mode"] = 0,
                    },
                },
                ["initial_outputs"] = {
                },
                ["name"] = "*scratchws*",
                ["type"] = "WGroupWS",
                ["unnumbered"] = true,
                ["sizepolicy"] = "full",
                ["level"] = 1,
                ["pseudomodal"] = true,
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["h"] = 2160,
                    ["w"] = 3840,
                    ["x"] = 0,
                },
            },
        },
    },
}

