-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["managed"] = {
            [1] = {
                ["level"] = 0,
                ["initial_outputs"] = {
                    [1] = "HDMI-0",
                },
                ["geom"] = {
                    ["w"] = 3840,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 2160,
                },
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["w"] = 3840,
                            ["x"] = 0,
                            ["y"] = 0,
                            ["h"] = 2160,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitST",
                            },
                            ["tls"] = 29,
                            ["type"] = "WSplitSplit",
                            ["brs"] = 2131,
                            ["br"] = {
                                ["tl"] = {
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 0,
                                                    ["hidden"] = true,
                                                    ["type"] = "WGroupCW",
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["w"] = 2565,
                                                        ["x"] = 1,
                                                        ["y"] = 19,
                                                        ["h"] = 1056,
                                                    },
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["level"] = 1,
                                                            ["windowid"] = 8388622,
                                                            ["type"] = "WClientWin",
                                                            ["sizepolicy"] = "full",
                                                            ["bottom"] = true,
                                                            ["geom"] = {
                                                                ["w"] = 2565,
                                                                ["x"] = 0,
                                                                ["y"] = 0,
                                                                ["h"] = 1056,
                                                            },
                                                            ["checkcode"] = 1,
                                                        },
                                                    },
                                                    ["name"] = "WGroupCW<2>",
                                                },
                                                [2] = {
                                                    ["level"] = 0,
                                                    ["switchto"] = true,
                                                    ["type"] = "WGroupCW",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["level"] = 1,
                                                            ["windowid"] = 27263012,
                                                            ["type"] = "WClientWin",
                                                            ["sizepolicy"] = "full",
                                                            ["bottom"] = true,
                                                            ["geom"] = {
                                                                ["w"] = 2564,
                                                                ["x"] = 0,
                                                                ["y"] = 4,
                                                                ["h"] = 1049,
                                                            },
                                                            ["checkcode"] = 2,
                                                        },
                                                    },
                                                    ["geom"] = {
                                                        ["w"] = 2565,
                                                        ["x"] = 1,
                                                        ["y"] = 19,
                                                        ["h"] = 1056,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["name"] = "WGroupCW<6>",
                                                },
                                            },
                                            ["mode"] = 1,
                                            ["name"] = "WFrame",
                                            ["type"] = "WFrame",
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["tls"] = 1076,
                                    ["type"] = "WSplitSplit",
                                    ["brs"] = 1055,
                                    ["br"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 0,
                                                    ["hidden"] = true,
                                                    ["type"] = "WGroupCW",
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["w"] = 2565,
                                                        ["x"] = 1,
                                                        ["y"] = 19,
                                                        ["h"] = 1035,
                                                    },
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["level"] = 1,
                                                            ["windowid"] = 12582913,
                                                            ["type"] = "WClientWin",
                                                            ["sizepolicy"] = "full",
                                                            ["bottom"] = true,
                                                            ["geom"] = {
                                                                ["w"] = 2565,
                                                                ["x"] = 0,
                                                                ["y"] = 0,
                                                                ["h"] = 1035,
                                                            },
                                                            ["checkcode"] = 3,
                                                        },
                                                    },
                                                    ["name"] = "WGroupCW",
                                                },
                                                [2] = {
                                                    ["level"] = 0,
                                                    ["hidden"] = true,
                                                    ["type"] = "WGroupCW",
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["w"] = 2565,
                                                        ["x"] = 1,
                                                        ["y"] = 19,
                                                        ["h"] = 1035,
                                                    },
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["level"] = 1,
                                                            ["windowid"] = 29360164,
                                                            ["type"] = "WClientWin",
                                                            ["sizepolicy"] = "full",
                                                            ["bottom"] = true,
                                                            ["geom"] = {
                                                                ["w"] = 2564,
                                                                ["x"] = 0,
                                                                ["y"] = 2,
                                                                ["h"] = 1030,
                                                            },
                                                            ["checkcode"] = 4,
                                                        },
                                                    },
                                                    ["name"] = "WGroupCW<7>",
                                                },
                                                [3] = {
                                                    ["level"] = 0,
                                                    ["switchto"] = true,
                                                    ["type"] = "WGroupCW",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["level"] = 1,
                                                            ["windowid"] = 25165860,
                                                            ["type"] = "WClientWin",
                                                            ["sizepolicy"] = "full",
                                                            ["bottom"] = true,
                                                            ["geom"] = {
                                                                ["w"] = 2564,
                                                                ["x"] = 0,
                                                                ["y"] = 2,
                                                                ["h"] = 1030,
                                                            },
                                                            ["checkcode"] = 5,
                                                        },
                                                    },
                                                    ["geom"] = {
                                                        ["w"] = 2565,
                                                        ["x"] = 1,
                                                        ["y"] = 19,
                                                        ["h"] = 1035,
                                                    },
                                                    ["sizepolicy"] = "full",
                                                    ["name"] = "WGroupCW<5>",
                                                },
                                            },
                                            ["mode"] = 1,
                                            ["name"] = "Tiling Frame",
                                            ["type"] = "WFrame",
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["dir"] = "vertical",
                                },
                                ["tls"] = 2567,
                                ["type"] = "WSplitSplit",
                                ["brs"] = 1273,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                            [1] = {
                                                ["level"] = 0,
                                                ["switchto"] = true,
                                                ["type"] = "WGroupCW",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["level"] = 1,
                                                        ["windowid"] = 20971556,
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["w"] = 1264,
                                                            ["x"] = 3,
                                                            ["y"] = 8,
                                                            ["h"] = 2094,
                                                        },
                                                        ["checkcode"] = 6,
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["w"] = 1271,
                                                    ["x"] = 1,
                                                    ["y"] = 19,
                                                    ["h"] = 2111,
                                                },
                                                ["sizepolicy"] = "full",
                                                ["name"] = "WGroupCW<3>",
                                            },
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "WFrame<1>",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "horizontal",
                            },
                            ["dir"] = "vertical",
                        },
                        ["name"] = "WTiling",
                    },
                },
                ["sizepolicy"] = "full",
                ["switchto"] = true,
                ["name"] = "WGroupWS",
            },
            [2] = {
                ["pseudomodal"] = true,
                ["name"] = "*scratchws*",
                ["geom"] = {
                    ["w"] = 3840,
                    ["x"] = 0,
                    ["y"] = 0,
                    ["h"] = 2160,
                },
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["level"] = 1025,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["w"] = 640,
                            ["x"] = 1600,
                            ["y"] = 840,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["mode"] = 0,
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["name"] = "*scratchpad*",
                    },
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["level"] = 1,
                ["hidden"] = true,
                ["unnumbered"] = true,
            },
        },
        ["name"] = "WScreen",
        ["type"] = "WScreen",
    },
}

